<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <DebugType>full</DebugType>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <DebugType>full</DebugType>
    </PropertyGroup>
    <ItemGroup>
      <None Remove="JSON\areas.json" />
      <None Remove="JSON\events.json" />
      <None Remove="JSON\items.json" />
      <None Remove="JSON\teleports.json" />
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Include="JSON\areas.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <EmbeddedResource Include="JSON\events.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <EmbeddedResource Include="JSON\items.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <EmbeddedResource Include="JSON\teleports.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.0" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>
</Project>
